DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE SELLER CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE ZZIM CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;
DROP TABLE TRADE_COM CASCADE CONSTRAINTS;
DROP TABLE CARD CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE CHAT CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE REVIEW_FILE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MNO; -- 회원번호 시퀀스
DROP SEQUENCE SEQ_SNO; -- 판매자번호 시퀀스
DROP SEQUENCE SEQ_BNO; -- 게시글번호 시퀀스 
DROP SEQUENCE SEQ_ANO; -- 첨부파일번호 시퀀스
DROP SEQUENCE SEQ_TRNO; -- 거래 시퀀스 
DROP SEQUENCE SEQ_RNO; -- 리뷰 시퀀스
DROP SEQUENCE SEQ_NNO; -- 공지사항 시퀀스
DROP SEQUENCE SEQ_ZNO; -- 찜 시퀀스 
DROP SEQUENCE SEQ_CNO; -- 채팅 시퀀스 
DROP SEQUENCE SEQ_DNO; -- 카드 시퀀스

COMMIT;

-- 멤버
CREATE TABLE MEMBER (
      MEMBER_NO NUMBER CONSTRAINT MEMBER_PK PRIMARY KEY NOT NULL,
      MEMBER_ID VARCHAR2(100) NOT NULL UNIQUE,
      MEMBER_PWD VARCHAR2(100) NOT NULL, 
      MEMBER_NAME VARCHAR2(100) NOT NULL,
      MEMBER_NICK VARCHAR2(100) NOT NULL UNIQUE,
      MEMBER_DATE DATE DEFAULT SYSDATE NOT NULL,
      MEMBER_PHONE VARCHAR2(12) NOT NULL,
      MEMBER_EMAIL VARCHAR2(100) NOT NULL UNIQUE,
      ADDRESS VARCHAR2(1000) NOT NULL,
      DETAIL_ADDRESS VARCHAR2(1000) NOT NULL,
      STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.MEMBER_NICK IS '회원닉네임';
COMMENT ON COLUMN MEMBER.MEMBER_DATE IS '가입일';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '휴대폰번호';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.DETAIL_ADDRESS IS '상세주소';
COMMENT ON COLUMN MEMBER.STATUS IS '상태';

CREATE SEQUENCE SEQ_MNO
NOCACHE;



-- 카테고리
CREATE TABLE CATEGORY(
  CATEGORY_NO NUMBER PRIMARY KEY,
  MAINCATEGORY_NAME VARCHAR2(50) NOT NULL,
  CATEGORY_NAME VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN CATEGORY.MAINCATEGORY_NAME IS '대분류';
COMMENT ON COLUMN CATEGORY.CATEGORY_NAME IS '소분류';



-- 등급
CREATE TABLE GRADE (	
    GRADE_NO NUMBER CONSTRAINT GRADE_PK PRIMARY KEY NOT NULL, 
	GRADE_NAME VARCHAR2(50 BYTE) NOT NULL
   );
   

-- 판매자
CREATE TABLE SELLER (	
    SELLER_NO NUMBER CONSTRAINT SELLER_PK PRIMARY KEY NOT NULL, 
	GRADE_NO NUMBER NOT NULL, 
	MEMBER_NO NUMBER NOT NULL, 
    CATEGORY_NO NUMBER NOT NULL, 
	CONTENTS VARCHAR2(4000) NOT NULL, 
	ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL, 
	ACCEPT_DATE DATE, 
	FILE_PATH VARCHAR2(2000) NOT NULL, 
	CAREER VARCHAR2(200) NOT NULL, 
	STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')) NOT NULL,
    FOREIGN KEY (GRADE_NO) REFERENCES GRADE(GRADE_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);
   
CREATE SEQUENCE SEQ_SNO
NOCACHE;


-- 판매 게시글
CREATE TABLE BOARD(
  BOARD_NO NUMBER PRIMARY KEY,
  SELLER_NO NUMBER NOT NULL,
  CATEGORY_NO NUMBER,
  BOARD_TITLE VARCHAR2(100) NOT NULL,
  LESSON_CONTENT VARCHAR2(4000) NOT NULL,
  CAREER VARCHAR2(4000) NOT NULL,
  BOARD_CONTENT VARCHAR2(4000) NOT NULL, 
  COUNT NUMBER DEFAULT 0,
  BOARD_WRITER VARCHAR2(100) NOT NULL,
  ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
  COST NUMBER NOT NULL,
  ST_DATE DATE NOT NULL,
  FN_DATE DATE NOT NULL,
  PLACE_CONTENT VARCHAR2(4000),
  FOREIGN KEY (BOARD_WRITER) REFERENCES MEMBER(MEMBER_NICK) ON DELETE SET NULL,
  FOREIGN KEY (SELLER_NO) REFERENCES SELLER(SELLER_NO),
  FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD.SELLER_NO IS '판매자번호';
COMMENT ON COLUMN BOARD.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.LESSON_CONTENT IS '레슨내용';
COMMENT ON COLUMN BOARD.CAREER IS '경력/이력';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '서비스상세내용';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN BOARD.ENROLL_DATE IS '등록일';
COMMENT ON COLUMN BOARD.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN BOARD.COST IS '가격';
COMMENT ON COLUMN BOARD.ST_DATE IS '서비스날짜시작일';
COMMENT ON COLUMN BOARD.FN_DATE IS '서비스날짜종료일';

CREATE SEQUENCE SEQ_BNO
NOCACHE;

CREATE TABLE ATTACHMENT (
  FILE_NO NUMBER PRIMARY KEY,
  BOARD_NO NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255),
  CHANGE_NAME VARCHAR2(255),
  FILE_PATH VARCHAR2(1000),
  FILE_SIZE NUMBER,
  FILE_TYPE  VARCHAR2(20),
  UPLOAD_DATE DATE DEFAULT SYSDATE NOT NULL,
  FILE_LEVEL NUMBER,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
  FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO)
);   



COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.BOARD_NO IS '참조게시글번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '저장폴더경로';
COMMENT ON COLUMN ATTACHMENT.FILE_SIZE IS '사진크기';
COMMENT ON COLUMN ATTACHMENT.FILE_TYPE IS '사진유형';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드일';
COMMENT ON COLUMN ATTACHMENT.FILE_LEVEL IS '파일레벨';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '상태값';

CREATE SEQUENCE SEQ_ANO
NOCACHE;

-- 찜
CREATE TABLE ZZIM (
	ZZIM_NO	  NUMBER		CONSTRAINT ZZIM_PK PRIMARY KEY,
	MEMBER_NO	NUMBER		NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),

  FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
  FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO)
);

CREATE SEQUENCE SEQ_ZNO 
NOCACHE;



-- 거래
CREATE TABLE TRADE_COM (	
    TRADE_NO NUMBER CONSTRAINT TRADE_PK PRIMARY KEY NOT NULL, 
	MEMBER_NO NUMBER NOT NULL, 
	BOARD_NO NUMBER NOT NULL, 
	TRADE_DATE DATE DEFAULT SYSDATE NOT NULL, 
	STATUS CHAR(1) CHECK (STATUS IN ('Y', 'N')) NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO)
   );
   
CREATE SEQUENCE SEQ_TRNO
NOCACHE;

-- 카드
CREATE TABLE CARD (
    CARD_NO VARCHAR2(100) CONSTRAINT CARD_PK PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    CARD_VALIDATE VARCHAR2(20) NOT NULL,
    CARD_PASSWORD NUMBER NOT NULL,
    CVC NUMBER NOT NULL,
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN CARD.CARD_NO IS '카드번호';
COMMENT ON COLUMN CARD.CARD_VALIDATE IS '카드유효기간';
COMMENT ON COLUMN CARD.CARD_PASSWORD IS '카드비밀번호';
COMMENT ON COLUMN CARD.CVC IS 'CVC';

CREATE SEQUENCE SEQ_DNO
NOCACHE;


-- 공지사항
CREATE TABLE NOTICE (
   NOTICE_NO NUMBER CONSTRAINT NOTICE_PK PRIMARY KEY NOT NULL,
   NOTICE_WRITER VARCHAR2(200) NOT NULL,
   NOTICE_TYPE VARCHAR2(200) NOT NULL,
   NOTICE_TITLE VARCHAR2(2000) NOT NULL,
   NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
   NOTICE_ENROLLDATE DATE NOT NULL,
   STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
   FOREIGN KEY (NOTICE_WRITER) REFERENCES MEMBER(MEMBER_ID)
);

CREATE SEQUENCE SEQ_NNO
        INCREMENT BY 1
        START WITH 1
        MINVALUE 1
        MAXVALUE 9999
        NOCYCLE
        NOCACHE;

ALTER TABLE NOTICE MODIFY (NOTICE_ENROLLDATE  DEFAULT SYSDATE);



COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지사항번호';
COMMENT ON COLUMN NOTICE.NOTICE_WRITER IS '작성자';
COMMENT ON COLUMN NOTICE.NOTICE_TYPE IS '공지사항타입';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.NOTICE_ENROLLDATE IS '등록일';
COMMENT ON COLUMN NOTICE.STATUS IS '상태';

-- 채팅
CREATE TABLE CHAT(
  CHAT_ID NUMBER NOT NULL PRIMARY KEY,
  FROM_NICK VARCHAR2(24) NOT NULL,
  TO_NICK VARCHAR2(24) NOT NULL,
  CHAT_CONTENT VARCHAR2(2000) NOT NULL,
  CHAT_TIME DATE DEFAULT SYSDATE,
  CHAT_READ CHAR(1) DEFAULT 'N' CHECK (CHAT_READ IN ('Y', 'N')) NOT NULL,
  CHAT_COUNT VARCHAR(100) DEFAULT NULL,
  FOREIGN KEY (FROM_NICK) REFERENCES MEMBER(MEMBER_NICK),
  FOREIGN KEY (TO_NICK) REFERENCES MEMBER(MEMBER_NICK)
);


CREATE SEQUENCE SEQ_CNO 
NOCACHE;

-- 리뷰
CREATE TABLE REVIEW (
	REVIEW_NO	NUMBER	CONSTRAINT REVIEW_PK PRIMARY KEY NOT NULL,
	BOARD_NO	NUMBER		NOT NULL,
	MEMBER_NO	NUMBER		NOT NULL,
	REVIEW_STAR	NUMBER		NOT NULL,
	REVIEW_TITLE	VARCHAR2(200)		NOT NULL,
	REVIEW_CONTENT	VARCHAR2(2000)		NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO),
    FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);

CREATE SEQUENCE SEQ_RNO
NOCACHE;

-- 리뷰 사진
CREATE TABLE "REVIEW_FILE" (
	IMG_NO	NUMBER CONSTRAINT IMG_PK PRIMARY KEY,
	REVIEW_NO	NUMBER		NOT NULL,
	ORIGIN_NAME	VARCHAR2(255)		NOT NULL,
	CHANGE_NAME	VARCHAR2(255)		NOT NULL,
	FILE_PATH	VARCHAR2(1000)		NOT NULL,
    STATUS CHAR(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    FOREIGN KEY (REVIEW_NO) REFERENCES REVIEW(REVIEW_NO)
);
DROP SEQUENCE SEQ_FNO;
CREATE SEQUENCE SEQ_FNO
NOCACHE;


COMMIT;
